artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_url: https://drive.google.com/file/d/1B5-P-c4HzOY1zs-118-k5QSW0fdh6cUW/view?usp=sharing
  dataset_raw: artifacts/data_ingestion/data.zip


data_validation:
  root_dir: artifacts/data_validation
  dataset_csv: artifacts/data_ingestion/heart.csv
  status_file: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  dataset_csv: artifacts/data_ingestion/heart.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_csv_file: artifacts/data_transformation/train.csv
  run_file: artifacts/model_trainer/stored_runs.txt
  model_name: model.joblib
  